---
- name: gnome-software role
  tags:
    - gnome-software
  block:

  - name: Apt state -> {{ gnome_software_apt_state }}
    become: true
    ansible.builtin.apt:
      name: gnome-software
      state: "{{ gnome_software_apt_state }}"

  - when: gnome_software_apt_state != "absent"
    ansible.builtin.import_tasks: state_present.yml